import 'package:supabase_flutter/supabase_flutter.dart';

import 'activity_models.dart';
import 'activity_engine.dart';

/// ===============================================================
/// HealthON — Notification Engine
///
/// ActivityEvent → Push Queue 등록 + Notification 저장 + Community 알림
/// ===============================================================

class NotificationEngine {
  NotificationEngine(this._client);

  final SupabaseClient _client;
  static const String _notificationTable = 'community_notifications';

  /// ActivityEvent를 Notification으로 변환하여 저장
  Future<String?> createFromActivity({
    required ActivityEvent event,
    required String userName,
    required String targetUserId,
  }) async {
    final engine = ActivityEngine(_client);
    final title = engine.feedTitle(event, userName);
    final body = engine.feedBody(event);

    try {
      final result = await _client.from(_notificationTable).insert({
        'user_id': targetUserId,
        'type': event.type.category,
        'title': title,
        'body': body ?? '',
        'data': {
          'eventId': event.id,
          'eventType': event.type.name,
          'userId': event.userId,
          'category': event.type.category,
          'isAutoGenerated': true,
        },
        'is_read': false,
      }).select('id').single();

      return result['id'] as String;
    } catch (e) {
      print('NotificationEngine: $e');
      return null;
    }
  }

  /// 여러 사용자에게 알림 발송 (멘션, 팔로우 등)
  Future<int> createMultiNotification({
    required String fromUserId,
    required String fromUserName,
    required List<String> toUserIds,
    required String type,
    required String titleTemplate,
    required String bodyTemplate,
    required Map<String, dynamic> data,
  }) async {
    int sent = 0;

    for (final toUserId in toUserIds) {
      try {
        await _client.from(_notificationTable).insert({
          'user_id': toUserId,
          'type': type,
          'title': titleTemplate.replaceAll('{from}', fromUserName),
          'body': bodyTemplate.replaceAll('{from}', fromUserName),
          'data': {
            'fromUserId': fromUserId,
            'fromUserName': fromUserName,
            ...data,
          },
          'is_read': false,
        });
        sent++;
      } catch (e) {
        print('NotificationEngine multi: $e');
      }
    }

    return sent;
  }

  /// 미읽음 알림 개수
  Future<int> getUnreadCount(String userId) async {
    try {
      final result = await _client
          .from(_notificationTable)
          .select('id')
          .eq('user_id', userId)
          .eq('is_read', false)
          .count(CountOption.exact);

      return result.count ?? 0;
    } catch (_) {
      return 0;
    }
  }

  /// 최근 알림 목록
  Future<List<Map<String, dynamic>>> getRecent(String userId, {int limit = 30}) async {
    try {
      final rows = await _client
          .from(_notificationTable)
          .select()
          .eq('user_id', userId)
          .order('created_at', ascending: false)
          .limit(limit);

      return (rows as List).cast<Map<String, dynamic>>();
    } catch (_) {
      return [];
    }
  }

  /// 읽음 처리
  Future<void> markAsRead(String notificationId) async {
    try {
      await _client
          .from(_notificationTable)
          .update({'is_read': true})
          .eq('id', notificationId);
    } catch (e) {
      print('NotificationEngine markAsRead: $e');
    }
  }

  /// 전체 읽음 처리
  Future<void> markAllAsRead(String userId) async {
    try {
      await _client
          .from(_notificationTable)
          .update({'is_read': true})
          .eq('user_id', userId)
          .eq('is_read', false);
    } catch (e) {
      print('NotificationEngine markAllAsRead: $e');
    }
  }
}
